/**
 * Gallery — imports the client's event photographs.
 *
 *   npm i --no-save sharp
 *   node scripts/import-gallery.mjs "C:/Users/va1ky/Downloads/gallery for nj/gallery for nj"
 *
 * Safe to re-run whenever photographs are added to the source folder. The
 * import is incremental and identified by file content:
 *
 *   - scripts/gallery-manifest.json remembers md5 -> output filename, so a
 *     photograph already imported keeps the same name and URL. Nothing is
 *     renumbered, and the alt text keyed to those names stays correct.
 *   - A photograph whose content matches one already imported is skipped,
 *     however it has been renamed or re-copied.
 *   - Only genuinely new photographs are resized and given the next number.
 *
 * Originals are phone-sized, so each is resized to 1000px on its long edge
 * and re-encoded as JPEG into public/img/gallery/. Orientation is read from
 * EXIF and baked in, because phone photos otherwise come out rotated once the
 * EXIF is stripped.
 *
 * Alt text lives in scripts/gallery-alt.json, keyed by output filename, and is
 * written by looking at the photographs. Anything without an entry falls back
 * to a plain description rather than an invented one — the run prints which
 * files still need one.
 */
import sharp from "sharp";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC = process.argv[2];
const OUT = "public/img/gallery";
const MANIFEST = "scripts/gallery-manifest.json";
const LONG_EDGE = 1000;

if (!SRC) {
  console.error("usage: node scripts/import-gallery.mjs <source folder>");
  process.exit(1);
}

const readJson = async (p, fallback) => {
  try {
    return JSON.parse(await readFile(p, "utf8"));
  } catch {
    return fallback;
  }
};

const ALT = await readJson("scripts/gallery-alt.json", {});
/** md5 -> output filename, from previous runs. */
const manifest = await readJson(MANIFEST, {});

await mkdir(OUT, { recursive: true });

const files = (await readdir(SRC))
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
  .sort();

// carry on numbering from whatever has already been imported
let next = Object.values(manifest).reduce((max, name) => {
  const n = Number(String(name).match(/(\d+)/)?.[1] ?? 0);
  return Math.max(max, n);
}, 0);

const order = [];
let added = 0,
  kept = 0,
  dupes = 0;

for (const file of files) {
  const buf = await readFile(path.join(SRC, file));
  const hash = createHash("md5").update(buf).digest("hex");

  const known = manifest[hash];
  if (known && existsSync(path.join(OUT, known))) {
    if (order.includes(known)) {
      dupes++; // same content under a second filename in the source folder
      continue;
    }
    order.push(known);
    kept++;
    continue;
  }

  const name = known || `flower-wall-${String(++next).padStart(2, "0")}.jpg`;
  await sharp(buf)
    .rotate() // bake in EXIF orientation before it is stripped
    .resize({ width: LONG_EDGE, height: LONG_EDGE, fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 78, mozjpeg: true })
    .toFile(path.join(OUT, name));
  manifest[hash] = name;
  order.push(name);
  added++;
  console.log("added", name, "<-", file);
}

const items = [];
for (const name of order) {
  const meta = await sharp(path.join(OUT, name)).metadata();
  items.push({
    src: `/img/gallery/${name}`,
    alt: ALT[name] || "Flower wall backdrop styled for an event in New Jersey",
    width: meta.width,
    height: meta.height,
  });
}

await writeFile(MANIFEST, JSON.stringify(manifest, null, 2) + "\n", "utf8");
await writeFile(
  "src/data/gallery.ts",
  `/**
 * Gallery photographs. Generated by scripts/import-gallery.mjs — edit that,
 * and scripts/gallery-alt.json for the alt text, not this file.
 */
export interface GalleryPhoto {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const GALLERY: GalleryPhoto[] = ${JSON.stringify(items, null, 2)};
`,
  "utf8",
);

const missing = order.filter((n) => !ALT[n]);
console.log(
  `\n${items.length} photos in the gallery — ${added} new, ${kept} already imported, ${dupes} duplicate skipped`,
);
if (missing.length) {
  console.log(`\nstill need alt text in scripts/gallery-alt.json:`);
  missing.forEach((n) => console.log("  " + n));
}
