/**
 * FAQs for the photo booth pages, keyed by the slug in `booths.ts`.
 *
 * Kept out of `booths.ts` because that file is generated by
 * scripts/import-booths.mjs and would overwrite anything written into it.
 *
 * Written per product: what it needs from the room, what guests get, and the
 * thing people are actually deciding between when they land on the page.
 * Space and power figures repeat where they are genuinely the same figure —
 * those are specifications, not copy.
 */

export const BOOTH_FAQS: Record<string, { q: string; a: string }[]> = {
  "360-photo-booth": [
    {
      q: "How much room does a 360 booth need?",
      a: "Roughly a 10ft x 10ft footprint with clearance on every side, because the arm sweeps a full circle around the platform. It is the largest footprint of anything we run, and worth checking against your floor plan before booking.",
    },
    {
      q: "How long does each guest take?",
      a: "About fifteen seconds on the platform, plus a moment to step on and off. The queue moves faster than people expect, and the attendant is there to keep it moving.",
    },
    {
      q: "Can guests share the video straight away?",
      a: "Yes — by text, email or QR code within moments of stepping off, which is what makes this booth spread across social feeds while the event is still running.",
    },
  ],

  "mirror-photo-booth": [
    {
      q: "What makes a mirror booth different from a standard booth?",
      a: "Guests see themselves full length in the mirror while it directs them, and they can sign or draw on the screen before printing. It is the most interactive of the print booths and it draws people in without an attendant having to coax them.",
    },
    {
      q: "How much space does it need?",
      a: "About 8ft x 8ft against a wall, plus a standard outlet within reach. That is comfortably less than a 360 platform, which is why it suits tighter rooms.",
    },
    {
      q: "Do guests get a physical print?",
      a: "Yes, on the night, plus a digital copy by text or email. Prints are the reason people still choose this booth over a purely digital one.",
    },
  ],

  "glam-photo-booth": [
    {
      q: "What is the glam look actually doing?",
      a: "Soft, even lighting with skin smoothing applied in camera — the black-and-white editorial finish people recognise from red-carpet portraits. It flatters everyone in the room, which is most of the appeal.",
    },
    {
      q: "Does it work in a dark venue?",
      a: "Yes. It brings its own lighting, so a dim reception room is not a problem — in fact controlled lighting is exactly what the look depends on.",
    },
    {
      q: "Is it better in colour or black and white?",
      a: "The signature finish is black and white and it is what most people book it for, but colour is available. You can decide when we set the template up rather than at booking.",
    },
  ],

  "branded-photo-booth": [
    {
      q: "What can we brand?",
      a: "The print template, the booth screen and the digital share — your logo travels with every photograph a guest sends on. For activations we can also wrap the booth surround itself.",
    },
    {
      q: "When do you need our artwork?",
      a: "A few days before the event, so there is time to proof it with you. Artwork arriving on the day is how placeholders end up on prints.",
    },
    {
      q: "Can we collect guest data at the booth?",
      a: "Where guests opt in at the point of sharing, yes — that is a standard part of how brand activations use these. We will set it up with whatever wording your team needs.",
    },
  ],

  "digital-photo-booth": [
    {
      q: "Is there a printer?",
      a: "This one is built around instant digital sharing rather than prints. If prints matter to you, the mirror or glam booths are the better choice and we will say so.",
    },
    {
      q: "How do guests receive their photos?",
      a: "By text, email or QR code, within moments. Digital-first booths tend to see more sharing than print booths, because the photograph goes straight to where people post it.",
    },
    {
      q: "How much space does it need?",
      a: "About 8ft x 8ft against a wall with a standard outlet in reach — the same as our other open-air booths.",
    },
  ],

  "video-booth": [
    {
      q: "What does a video booth capture?",
      a: "Short video clips rather than stills — guests record a message or a moment, and the result is something you watch back rather than pin to a fridge.",
    },
    {
      q: "Can guests leave a message for the couple?",
      a: "Yes, and it is the most common way this booth gets used at weddings. It replaces the guest book people never read with something they actually will.",
    },
    {
      q: "Do we get all the footage afterwards?",
      a: "Yes — the full set is delivered after the event, along with the individual clips guests shared on the night.",
    },
  ],

  "mirror-x-photo-booth": [
    {
      q: "How is the Mirror X different from the standard mirror booth?",
      a: "It is the larger, more modern build of the same idea — a bigger screen, a sleeker surround and a more current interface. If the booth is going somewhere it will be seen as much as used, this is the one.",
    },
    {
      q: "Does it still print?",
      a: "Yes, prints on the night plus digital sharing, the same as the standard mirror booth.",
    },
    {
      q: "Is it worth the upgrade for a small party?",
      a: "Honestly, often not. In a small room the standard mirror booth does the same job. The Mirror X earns its place in larger spaces and at events where the booth is part of the styling.",
    },
  ],

  "roaming-photo-booth": [
    {
      q: "How does a roaming booth work?",
      a: "An attendant carries a handheld unit around the room and photographs guests where they already are, rather than waiting for them to come to a corner. It reaches the people who would never queue.",
    },
    {
      q: "Does it need floor space?",
      a: "Almost none, which is the point. For venues with no spare corner, or seated dinners where nobody wants to get up, it is usually the only booth that works.",
    },
    {
      q: "Do guests still get their photos instantly?",
      a: "Yes — sharing happens on the spot, by text or QR, before the attendant moves on to the next table.",
    },
  ],

  "green-screen-photo-booth": [
    {
      q: "Can we choose the background?",
      a: "Yes — any background you supply or choose in advance, swapped in live. It is how you put guests somewhere the venue is not.",
    },
    {
      q: "Do we still need a backdrop in the room?",
      a: "A green screen comes with its own. What it does mean is that a flower wall is not required behind this particular booth, so it is worth deciding which effect you actually want rather than paying for both.",
    },
    {
      q: "Does it work with any outfit colour?",
      a: "Almost — the one thing to avoid is guests wearing the same green as the screen, which is rare enough that it has never actually caused us a problem.",
    },
  ],

  "mosaic-wall": [
    {
      q: "What is a mosaic wall?",
      a: "Every photograph taken during the event becomes one tile in a single large image that fills in live as the night goes on. Guests come back to watch it complete.",
    },
    {
      q: "What image does it build?",
      a: "Whatever you choose — a monogram, a logo, a portrait of the couple. We set it up from artwork you supply ahead of the event.",
    },
    {
      q: "Do we keep it afterwards?",
      a: "Yes, both the finished mosaic and the individual photographs that make it up.",
    },
  ],

  "ai-photo-booth": [
    {
      q: "What does the AI booth actually do?",
      a: "It transforms a guest's photograph into a styled portrait using themes chosen ahead of the event, so people leave with something they could not have taken themselves.",
    },
    {
      q: "How long does each guest wait?",
      a: "Longer than a standard booth — the image has to be generated. It is worth knowing when planning: this booth rewards a smaller crowd or a longer running time rather than a rush of two hundred people at once.",
    },
    {
      q: "Can we choose the styles in advance?",
      a: "Yes, and you should. Themes are agreed before the event so they suit the occasion rather than being picked at random on the night.",
    },
  ],

  glambot: [
    {
      q: "What is a glambot?",
      a: "A robotic camera arm that sweeps past guests capturing high-frame-rate slow motion — the cinematic shot you see on award-show carpets. It produces the most dramatic clip of anything we run.",
    },
    {
      q: "How much space does it need?",
      a: "A clear run for the arm plus room for guests to stand, so plan for a generous footprint. Send us the floor plan and we will confirm it fits before you commit.",
    },
    {
      q: "Is it better for brand events or private parties?",
      a: "Both, though it earns its keep most where the resulting clip gets used afterwards — activations, launches, and any event where the footage has a life beyond the night.",
    },
  ],

  "magazine-booth": [
    {
      q: "What does a magazine booth produce?",
      a: "Prints laid out as a magazine cover, with your own title, cover lines and styling. Guests leave holding something that looks published rather than photographed.",
    },
    {
      q: "Can the cover be customised to our event?",
      a: "Yes — the masthead, the cover lines and the colours are all set up in advance to match the occasion or the brand.",
    },
    {
      q: "Is it a print or a digital booth?",
      a: "Both. The print is the point, but guests also get a digital copy to share.",
    },
  ],

  "gif-booth": [
    {
      q: "What is a GIF booth?",
      a: "It captures a short burst of frames and loops them, so guests get a moving image rather than a still. They share far more readily than photographs, because a loop is more fun to post.",
    },
    {
      q: "Can guests still get a print?",
      a: "A loop cannot be printed, so this booth is digital by nature. Where you want both, pair it with a print booth or choose a booth that does both.",
    },
    {
      q: "What kind of event suits it?",
      a: "Younger crowds and anything where social sharing is the goal. It is one of the highest-sharing formats we run.",
    },
  ],

  "3d-slider-booth": [
    {
      q: "What does the 3D slider produce?",
      a: "A camera slides past the group capturing a sequence that plays back with a genuine sense of depth — a still that moves around the subject rather than a video of it.",
    },
    {
      q: "How many people fit in one shot?",
      a: "It works best with small groups, two to four, because the depth effect depends on the camera passing cleanly across the subject. Large groups flatten it out.",
    },
    {
      q: "Is it a print or digital format?",
      a: "Digital — the effect only exists in motion, so it is shared rather than printed.",
    },
  ],

  "studio-booth": [
    {
      q: "How is a studio booth different from an open-air booth?",
      a: "Studio lighting and a controlled setup produce something closer to a portrait session than a party snapshot. It is the choice when the photographs need to look considered.",
    },
    {
      q: "Is an attendant included?",
      a: "Yes, and here it matters more than usual — someone directing guests is a large part of why studio results look better than a self-serve booth.",
    },
    {
      q: "What space does it need?",
      a: "More depth than a standard booth, because the lighting has to sit off the subject. Send us the room dimensions and we will confirm it works before you book.",
    },
  ],
};
