/**
 * "Events that Bloomed" carousel slides. Generated by
 * scripts/import-event-slides.mjs — edit that, not this.
 *
 * The ornate gold frame is part of each photograph, so the slides render
 * without a border of their own.
 */
export interface EventSlide {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const EVENT_SLIDES: EventSlide[] = [
  {
    "src": "/legacy/events/champagne-pommery-greenery-wall.jpg",
    "alt": "Guest in a sequinned gown posing at a white and greenery flower wall lit by a Champagne Pommery neon sign",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/evanta-corporate-greenery-wall.jpg",
    "alt": "Boxwood greenery wall crowned with mixed florals and an illuminated Evanta, a Gartner Company logo",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/ritz-carlton-blue-flower-wall.jpg",
    "alt": "Three guests photographed at a blue and white flower wall beneath a Ritz-Carlton sign",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/inside-beauty-forum-hedge-wall.jpg",
    "alt": "Inside Beauty Forum neon logo mounted on a bright green hedge wall",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/ombre-rose-flower-wall.jpg",
    "alt": "Ombre rose wall fading from deep magenta through blush to ivory, styled in a private home",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/wedding-sweetheart-table-floral.jpg",
    "alt": "Outdoor wedding sweetheart table with white thrones set against a white floral backdrop",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/red-pink-garden-rose-wall.jpg",
    "alt": "Four guests posing together in front of a red and pink garden rose wall",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/blush-rose-wall-neon-bar.jpg",
    "alt": "Blush rose wall with a custom pink neon sign behind an event bar",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/black-tie-reception-tablescape.jpg",
    "alt": "Reception tablescape in black and blush with gold chargers and a dark floral backdrop",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/betsey-johnson-pink-rose-wall.jpg",
    "alt": "Pink rose wall with a Betsey Johnson neon sign and a hot pink sofa at a trade show booth",
    "width": 750,
    "height": 500
  },
  {
    "src": "/legacy/events/wedding-welcome-sign-roses.jpg",
    "alt": "Black wedding welcome sign topped with roses at a stone venue entrance",
    "width": 750,
    "height": 500
  }
];
