/**
 * Gallery photographs. Generated by scripts/import-gallery.mjs — edit that,
 * and scripts/gallery-alt.json for the alt text, not this file.
 */
export interface GalleryPhoto {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const GALLERY: GalleryPhoto[] = [
  {
    "src": "/img/gallery/flower-wall-01.jpg",
    "alt": "Red rose heart-shaped arch set against an ivory ballroom wall",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-02.jpg",
    "alt": "Tropical greenery wall with a gold Let's Party neon sign, set up on a back lawn",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-03.jpg",
    "alt": "Speaker with a microphone in front of a greenery wall lit by a Bio Hackers World neon sign",
    "width": 800,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-04.jpg",
    "alt": "Presenter on stage in front of a greenery wall with a Bio Hackers World neon sign",
    "width": 802,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-05.jpg",
    "alt": "Conference speaker presenting against a greenery wall backdrop",
    "width": 802,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-06.jpg",
    "alt": "Presenter beside a screen with a greenery wall filling the stage behind",
    "width": 800,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-07.jpg",
    "alt": "Full audience at a conference styled with greenery wall backdrops",
    "width": 802,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-08.jpg",
    "alt": "Panel interview in a lounge set framed by greenery walls",
    "width": 800,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-09.jpg",
    "alt": "Speaker mid-talk in front of a lit greenery wall",
    "width": 800,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-10.jpg",
    "alt": "Couple photographed inside a red rose heart arch with a Will You Marry Me neon sign",
    "width": 806,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-11.jpg",
    "alt": "Marriage proposal on one knee at a red rose heart arch, red carpet underfoot",
    "width": 803,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-12.jpg",
    "alt": "Group photograph taken against a greenery wall at a New York conference",
    "width": 800,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-13.jpg",
    "alt": "Pastel garden wall of eucalyptus, roses and blossom with a gold acrylic sign",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-14.jpg",
    "alt": "Eucalyptus and blush rose garden wall dressed for a summit reception",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-15.jpg",
    "alt": "Guest posing at a mauve and blush rose wall with a Summer Social sign, brick venue",
    "width": 563,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-16.jpg",
    "alt": "Mauve and blush rose wall with a burgundy Summer Social sign in a brick venue",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-17.jpg",
    "alt": "Angled view of a blush and mauve rose wall in a brick-arched venue",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-18.jpg",
    "alt": "Close view of the Summer Social sign set into a mauve rose wall",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-19.jpg",
    "alt": "Tropical greenery wall with a Sherwin-Williams and Suvinil neon sign",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-20.jpg",
    "alt": "Greenery wall carrying a lit Sherwin-Williams and Suvinil brand sign",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-21.jpg",
    "alt": "Brand-lit greenery wall glowing in a darkened event room",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-22.jpg",
    "alt": "Yellow and orange rose wall beside a photo booth in a hotel ballroom",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-23.jpg",
    "alt": "Yellow and orange rose wall with photo booth and printer station set up",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-24.jpg",
    "alt": "Citrus rose wall paired with an open-air photo booth",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-25.jpg",
    "alt": "Guests posing together at a blue hydrangea wall beside a photo booth",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-26.jpg",
    "alt": "Guest in a red dress photographed at a yellow and orange rose wall",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-27.jpg",
    "alt": "Guest posing at a citrus rose wall while the booth attendant works",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-28.jpg",
    "alt": "Guests queueing at a photo booth in front of a yellow and orange rose wall",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-29.jpg",
    "alt": "Family group photographed at a citrus rose wall",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-30.jpg",
    "alt": "Four guests in evening dress at a blue floral wall",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-31.jpg",
    "alt": "Couple posing together at a blue floral wall",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-32.jpg",
    "alt": "Guests gathering for a group shot at a blue floral wall",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-33.jpg",
    "alt": "Attendant setting up a group photograph at a blue floral wall",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-34.jpg",
    "alt": "Greenery walls framing a lounge set with leather armchairs for filmed interviews",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-35.jpg",
    "alt": "Interview lounge built between two greenery walls under studio lighting",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-36.jpg",
    "alt": "Pale blue floral wall with a Something Blue Before I Do neon sign",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-37.jpg",
    "alt": "Blue and cream floral wall set beside picture windows for a bridal shower",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-38.jpg",
    "alt": "Blue floral wall with a pink neon sign in a light-filled room",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-39.jpg",
    "alt": "Guest holding a speaker poster in front of a greenery wall",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-40.jpg",
    "alt": "Greenery wall carrying a brand logo in a darkened ballroom",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-41.jpg",
    "alt": "Tall greenery wall with an illuminated brand logo",
    "width": 1000,
    "height": 750
  },
  {
    "src": "/img/gallery/flower-wall-42.jpg",
    "alt": "Mother and baby photographed at a soft pink floral wall",
    "width": 750,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-43.jpg",
    "alt": "Burgundy and blush rose wall carrying a corporate logo sign",
    "width": 1000,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-44.jpg",
    "alt": "Deep red and pink rose wall with a branded sign at its centre",
    "width": 1000,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-45.jpg",
    "alt": "Branded rose wall styled with candles in a loft space",
    "width": 1000,
    "height": 1000
  },
  {
    "src": "/img/gallery/flower-wall-46.jpg",
    "alt": "Ivory floral arch framing a window, with chairs and candlelight beneath",
    "width": 1000,
    "height": 750
  }
];
